config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    get 'join', on: :member
    get 'drop', on: :member
    get 'new_message', on: :member
    post 'send_message', on: :member
    get 'new_document', on: :member
    post 'upload_document', on: :member
  end
  resources :users do
    get 'new_message', on: :member
    post 'send_message', on: :member
  end
  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'login', to: 'users#postlogin'
  resources :messages
  resources :documents
  root 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :group
  attr_accessor :content

  validates :filename,
    presence: true,
    length: { maximum: 20 }

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
  has_many :documents

  validates :groupname,
    uniqueness: true,
    presence: true,
    length: { maximum: 20 }
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user,
    uniqueness: { scope: :group }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :from_user, class_name: 'User'
  belongs_to :to_user, class_name: 'User'

  validates :from_user,
    presence: true

  validates :to_user,
    presence: true

  validates :title,
    presence: true,
    length: { maximum: 100 }

  validates :content,
    presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :sent_messages,
    class_name: "Message",
    foreign_key: "from_user"
  has_many :recieved_messages,
    class_name: "Message",
    foreign_key: "to_user"

  validates :username,
    presence: true,
    uniqueness: true,
    length: { maximum: 20 }

  validates :nickname,
    presence: true,
    length: { maximum: 20 }

  validates :password,
    presence: true,
    confirmation: true,
    length: { maximum: 20 }

  validates :password_confirmation,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    render 'layouts/index'
  end
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      @user = User.find(session[:uid])
      Membership.new({user: @user, group: @group}).save
      redirect_to @group
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:id])
    @user = User.find(session[:uid])
    Membership.new({user: @user, group: @group}).save
    redirect_to(:back)
  end

  def drop
    @group = Group.find(params[:id])
    @user = User.find(session[:uid])
    @group.users.delete(@user)
    redirect_to(:back)
  end

  def new_message
    @group = Group.find(params[:id])
    @message = Message.new
  end

  def send_message
    @group = Group.find(params[:id])
    @group.users.each do |user|
      @message = Message.new(message_params)
      @message.from_user = User.find(session[:uid])
      @message.to_user = User.find(user.id)
      @message.save!
    end
    redirect_to(user_path(session[:uid]))
  end

  def new_document
    @group = Group.find(params[:id])
    @document = Document.new
  end

  def upload_document
    @group = Group.find(params[:id])
    @document = Document.new(document_params)
    upload_file = params[:document][:content]
    @document.filename = upload_file.original_filename
    @document.group = @group
    @document.save!
    File.open(document_file_path(@document), 'wb') do |file|
      file.write(upload_file.read)
    end
    redirect_to(group_path(@group))
  end

  private
  def group_params
    params.require(:group).permit(:groupname)
  end

  private
  def message_params
    params.require(:message).permit(:title, :content)
  end

  private
  def document_params
    params.require(:document).permit(:content)
  end

  private
  def document_file_path(document)
    Rails.root.join('public', 'uploads', String(document.id) + File.extname(document.filename))
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @message = Message.find(params[:id])
    if not session[:uid] or not (session[:uid] == @message.to_user.id or session[:uid] == @message.from_user.id)
      redirect_to(root_url)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to user_path(session[:uid])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:uid] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.id != session[:uid]
      redirect_to(:back)
    end
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if @user.id != session[:uid]
      redirect_to(:back)
    end
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  def login
    @user = User.new
  end

  def postlogin
    @user = User.where(username: User.new(user_params).username, password: User.new(user_params).password).take
    if @user
      session[:uid] = @user.id
      redirect_to @user
    else
      redirect_to(:back)
    end
  end

  def logout
    session[:uid] = nil
    redirect_to root_url
  end

  def new_message
    @user = User.find(params[:id])
    @message = Message.new
  end

  def send_message
    @message = Message.new(message_params)
    @message.from_user = User.find(session[:uid])
    @message.to_user = User.find(params[:id])
    @message.save!
    redirect_to(users_path(@message.from_user))
  end

  private
  def user_params
    params.require(:user).permit(:username, :nickname, :password, :password_confirmation)
  end

  private
  def login_params
    params.require(:user).permit(:username, :password)
  end

  private
  def message_params
    params.require(:message).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def document_url_path(document)
    '/uploads/' + String(document.id) + File.extname(document.filename)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        填写的该表单有<%= @group.errors.count %>个错误
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :groupname, "小组名" %><br>
    <%= f.text_field :groupname %>
  </p>
  <p>
    <%= f.submit "提交" %>
  </p>
<% end %>

app/views/groups/edit.html.erb
<h1>编辑小组</h1>
<%= render 'form' %>
<%= link_to "返回", group_path(@group) %>
<%= link_to "查看小组列表", groups_path %>

app/views/groups/index.html.erb
<h1>小组列表</h1>
<ul>
  <% @groups.each do |group| %>
    <li><%= link_to (group.groupname), group_path(group) %></li>
  <% end %>
</ul>
<% if session[:uid] %>
  <%= link_to "创建小组", new_group_path %>
<% end %>

app/views/groups/new.html.erb
<h1>创建小组</h1>
<%= render 'form' %>
<%= link_to "查看小组列表", groups_path %>

app/views/groups/new_document.html.erb
<%= form_for @document, action: 'post', url: upload_document_group_url(@group) do |f| %>
  <p>
    <strong>选择文件</strong>
    <br>
    <%= f.file_field :content %>
  </p>
  <p>
    <%= f.submit "发送" %>
  </p>
<% end %>

app/views/groups/new_message.html.erb
<%= form_for @message, action: 'post', url: send_message_group_url(@group) do |f| %>
  <p>
    <strong>标题</strong>
    <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <strong>内容</strong>
    <br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "发送" %>
  </p>
<% end %>

app/views/groups/show.html.erb
<h1>小组查看页面</h1>
<p>
  <strong>小组名</strong>
  <%= @group.groupname %>
</p>
<p>
  <%= @group.users.count() %>个用户
  <table>
    <thead>
      <tr>
        <td>用户名</td>
        <td>昵称</td>
      </tr>
    <tbody>
      <% @group.users.each() do |user| %>
        <tr>
          <td><%= link_to user.username, user_path(user) %></td>
          <td><%= user.nickname %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @group.users.exists?(session[:uid]) %>
    <p>
      <%= @group.documents.count() %>个共享文件
      <ul>
        <% @group.documents.each do |document| %>
          <li><%= link_to document.filename, document_url_path(document) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
</p>
<% if session[:uid] %>
  <% if @group.users.count == 0 or @group.users.first.id == session[:uid] %>
    <%= link_to "编辑小组", edit_group_path(@group) %>
    <%= link_to '删除小组', group_path(@group),
      method: :delete,
      data: { confirm: '您确定吗？' } %>
  <% elsif @group.users.exists?(session[:uid]) %>
    <%= link_to "离开小组", drop_group_path(@group) %>
  <% end %>

  <% if not @group.users.exists?(session[:uid]) %>
    <%= link_to "加入小组", join_group_path(@group) %>
  <% end %>
<% end %>

<% if session[:uid] %>
  <%= link_to "发送邮件", new_message_group_url(@group) %>
  <%= link_to "上传文件", new_document_group_url(@group) %>
<% end %>
<%= link_to "查看小组列表", groups_path %>

app/views/layouts/_status.html.erb
<p>
  <% if session[:uid] %>
    <strong>欢迎您</strong>
    <%= link_to User.find(session[:uid]).username, user_path(User.find(session[:uid])) %>
    (<%= User.find(session[:uid]).nickname %>)
    <%= link_to "登出", logout_url %>
  <% else %>
    <strong>欢迎您，请</strong>
    <%= link_to "登录", login_url %>
    <strong>或</strong>
    <%= link_to "注册", new_user_url %>
  <% end %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to "用户列表", users_url %>
  <%= link_to "小组列表", groups_url %>
  <%= link_to "主页", root_url %>
</p>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fileshare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/status' %>
    <%= yield %>
    <hr>
    <p><strong>文件分享系统</strong> 作者: 软件51 沈俞霖 2151601013</p>
  </body>
</html>

app/views/layouts/index.html.erb
<h1>欢迎使用文件分享系统</h1>

app/views/messages/show.html.erb
<p>
  <strong>发件人</strong>
  <%= @message.from_user.username %>(<%= @message.from_user.nickname %>)
</p>
<p>
  <strong>收件人</strong>
  <%= @message.to_user.username %>(<%= @message.to_user.nickname %>)
</p>
<p>
  <strong>标题</strong>
  <%= @message.title %>
</p>
<p>
  <strong>内容</strong>
  <pre><%= @message.content %></pre>
</p>
<% if session[:uid] == @message.to_user.id %>
  <%= link_to '删除邮件', message_path(@message),
    method: :delete,
    data: { confirm: '您确定吗？' } %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        填写的该表单有<%= @user.errors.count %>个错误
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :username, "用户名" %><br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :nickname, "昵称" %><br>
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :password, "密码" %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "确认密码" %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "提交" %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>编辑用户</h1>
<%= render 'form' %>
<%= link_to "返回", user_path(@user) %>
<%= link_to "查看用户列表", users_path %>

app/views/users/index.html.erb
<h1>用户列表</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to (user.username), user_path(user) %></li>
  <% end %>
</ul>

app/views/users/login.html.erb
<h1>登录</h1>
<%= form_for :user do |f| %>
  <p>
    <%= f.label :username, "用户名" %><br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password, "密码" %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit "提交" %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>创建用户</h1>
<%= render 'form' %>

app/views/users/new_message.html.erb
<%= form_for @message, action: 'post', url: send_message_user_url(@user) do |f| %>
  <p>
    <strong>标题</strong>
    <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <strong>内容</strong>
    <br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "发送" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>用户查看页面</h1>
<p>
  <strong>用户名</strong>
  <%= @user.username %>
</p>
<p>
  <strong>昵称</strong>
  <%= @user.nickname %>
</p>
<p>
  <%= @user.groups.count() %>个小组
  <ul>
    <% @user.groups.each() do |group| %>
      <li><%= link_to group.groupname, group_path(group) %></li>
    <% end %>
  </ul>
</p>
<% if session[:uid] and @user.id == session[:uid] %>
  <p>
    <%= @user.recieved_messages.count() %>个收到邮件
    <ul>
      <% @user.recieved_messages.all.each do |message| %>
        <li><%= link_to message.title, message_path(message) %></li>
      <% end %>
    </ul>
  </p>
  <p>
    <%= @user.sent_messages.count() %>个发出邮件
    <ul>
      <% @user.sent_messages.all.each do |message| %>
        <li><%= link_to message.title, message_path(message) %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<% if @user.id == session[:uid] %>
  <%= link_to "编辑用户", edit_user_path(@user) %>
  <%= link_to '删除用户', user_path(@user),
                method: :delete,
                data: { confirm: '您确定吗？' } %>
<% end %>
<% if session[:uid] %>
  <%= link_to "发送邮件", new_message_user_url(@user) %>
<% end %>
<%= link_to "查看用户列表", users_path %>